# Generated by Django 5.0 on 2025-01-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_id", models.IntegerField(db_index=True)),
                ("human_presence", models.BooleanField()),
                ("dwell_time", models.FloatField()),
                ("timestamp", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
